on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
      - converted_to_draft
      - review_requested
  push:
    branches:
      - 1.x

jobs:
  run:
    name: php-cs-fixer
    runs-on: ${{ matrix.operating-systems }}

    strategy:
      fail-fast: false
      matrix:
        operating-systems:
          - ubuntu-latest
        php-versions:
          - 8.1

    steps:
      - uses: actions/checkout@v3
      - uses: docker://ergebnis/composer-normalize-action
