name: "PEST"

on:
  pull_request_target: {}
  push:
    branches:
      - 1.x

jobs:
  pest:
    name:
    runs-on: ${{ matrix.operating-systems }}

    strategy:
      fail-fast: false
      matrix:
        operating-systems:
          - ubuntu-latest
        php-versions:
          - 8.1

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: pcov
          extensions: mbstring

      - id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - run: composer install --no-progress --prefer-dist --optimize-autoloader

      - run: vendor/bin/pest --order-by random --compact

      - uses: codecov/codecov-action@v3
        with:
          directory: ./coverage/
          flags: unittests
